#############################################################################
# Makefile for building: pdfwidgets
# Generated by qmake (3.1) (Qt 5.15.10)
# Project:  pdfwidgets.pro
# Template: subdirs
# Command: H:\Qt\Qt5.15.10-release\bin\qmake.exe -o Makefile pdfwidgets.pro -spec win32-msvc "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = H:\Qt\Qt5.15.10-release\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = H:\Qt\Qt5.15.10-release\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = H:\Qt\Qt5.15.10-release\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-pdfviewer


sub-pdfviewer-qmake_all:  FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	cd pdfviewer\ && $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && $(MAKE) -f Makefile qmake_all
sub-pdfviewer: $(MAKEFILE) FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-pdfviewer-make_first: FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-pdfviewer-all: FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-pdfviewer-clean: FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-pdfviewer-distclean: FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-pdfviewer-install_subtargets: FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-pdfviewer-uninstall_subtargets: FORCE
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: pdfwidgets.pro H:\Qt\Qt5.15.10-release\mkspecs\win32-msvc\qmake.conf H:\Qt\Qt5.15.10-release\mkspecs\features\spec_pre.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\common\angle.conf \
		H:\Qt\Qt5.15.10-release\mkspecs\common\windows-desktop.conf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\win32\windows_vulkan_sdk.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\common\windows-vulkan.conf \
		H:\Qt\Qt5.15.10-release\mkspecs\common\msvc-desktop.conf \
		H:\Qt\Qt5.15.10-release\mkspecs\qconfig.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_freetype.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libEGL.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libGLESv2.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libjpeg.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libpng.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3danimation.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3danimation_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dcore.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dcore_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dextras.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dextras_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dinput.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dinput_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dlogic.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dlogic_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquick.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquick_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickanimation.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickextras.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickinput.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickrender.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3drender.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3drender_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axbase.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axbase_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axcontainer.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axcontainer_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axserver.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axserver_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bluetooth.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bluetooth_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bodymovin_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bootstrap_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_charts.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_charts_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_concurrent.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_concurrent_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_core.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_core_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_datavisualization.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_datavisualization_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_dbus.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_dbus_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_designer.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_designer_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_designercomponents_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_edid_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_egl_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_fb_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gamepad.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gamepad_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gui.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gui_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_help.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_help_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_location.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_location_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimedia.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimedia_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimediawidgets.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_network.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_network_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_networkauth.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_networkauth_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_nfc.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_nfc_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_opengl.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_opengl_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_openglextensions.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_openglextensions_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdf.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdf_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdfwidgets.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdfwidgets_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioning.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioning_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioningquick.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioningquick_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_printsupport.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_printsupport_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_purchasing.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_purchasing_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qml.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qml_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmldebug_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlmodels.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmltest.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmltest_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3d.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3d_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3drender.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3drender_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dutils.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickcontrols2.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickparticles_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickshapes_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quicktemplates2.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickwidgets.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_remoteobjects.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_repparser.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_repparser_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_scxml.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_scxml_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sensors.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sensors_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialbus.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialbus_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialport.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialport_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sql.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sql_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_svg.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_svg_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_testlib.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_testlib_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_texttospeech.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_texttospeech_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_theme_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_uiplugin.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_uitools.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_uitools_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webchannel.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webchannel_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webengine.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webengine_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginecore.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginecore_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginewidgets.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_websockets.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_websockets_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webview.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webview_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_widgets.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_widgets_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_winextras.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_winextras_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_xml.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_xml_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_zlib_private.pri \
		H:\Qt\Qt5.15.10-release\mkspecs\features\qt_functions.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\qt_config.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\win32-msvc\qmake.conf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\spec_post.prf \
		.qmake.stash \
		H:\Qt\Qt5.15.10-release\mkspecs\features\exclusive_builds.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\common\msvc-version.conf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\toolchain.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\default_pre.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\win32\default_pre.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\resolve_config.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\exclusive_builds_post.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\default_post.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\qml_debug.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\precompile_header.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\warn_on.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\qmake_use.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\file_copies.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\win32\windows.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\testcase_targets.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\exceptions.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\yacc.prf \
		H:\Qt\Qt5.15.10-release\mkspecs\features\lex.prf \
		pdfwidgets.pro
	$(QMAKE) -o Makefile pdfwidgets.pro -spec win32-msvc "CONFIG+=qml_debug"
H:\Qt\Qt5.15.10-release\mkspecs\features\spec_pre.prf:
H:\Qt\Qt5.15.10-release\mkspecs\common\angle.conf:
H:\Qt\Qt5.15.10-release\mkspecs\common\windows-desktop.conf:
H:\Qt\Qt5.15.10-release\mkspecs\features\win32\windows_vulkan_sdk.prf:
H:\Qt\Qt5.15.10-release\mkspecs\common\windows-vulkan.conf:
H:\Qt\Qt5.15.10-release\mkspecs\common\msvc-desktop.conf:
H:\Qt\Qt5.15.10-release\mkspecs\qconfig.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_freetype.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libEGL.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libGLESv2.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libjpeg.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_ext_libpng.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3danimation.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3danimation_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dcore.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dcore_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dextras.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dextras_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dinput.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dinput_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dlogic.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dlogic_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquick.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquick_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickanimation.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickextras.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickextras_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickinput.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickinput_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickrender.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickrender_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickscene2d.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3drender.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_3drender_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_accessibility_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axbase.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axbase_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axcontainer.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axcontainer_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axserver.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_axserver_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bluetooth.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bluetooth_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bodymovin_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_bootstrap_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_charts.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_charts_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_concurrent.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_concurrent_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_core.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_core_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_datavisualization.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_datavisualization_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_dbus.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_dbus_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_designer.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_designer_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_designercomponents_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_edid_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_egl_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_fb_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gamepad.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gamepad_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gui.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_gui_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_help.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_help_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_location.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_location_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimedia.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimedia_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimediawidgets.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_network.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_network_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_networkauth.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_networkauth_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_nfc.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_nfc_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_opengl.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_opengl_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_openglextensions.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_openglextensions_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_packetprotocol_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdf.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdf_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdfwidgets.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_pdfwidgets_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioning.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioning_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioningquick.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_positioningquick_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_printsupport.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_printsupport_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_purchasing.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_purchasing_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qml.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qml_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmldebug_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmldevtools_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlmodels.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlmodels_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmltest.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmltest_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlworkerscript.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3d.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3d_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dassetimport.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3drender.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3drender_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3druntimerender.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dutils.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick3dutils_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quick_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickcontrols2.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickparticles_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickshapes_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quicktemplates2.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickwidgets.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_quickwidgets_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_remoteobjects.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_remoteobjects_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_repparser.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_repparser_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_scxml.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_scxml_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sensors.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sensors_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialbus.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialbus_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialport.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_serialport_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sql.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_sql_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_svg.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_svg_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_testlib.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_testlib_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_texttospeech.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_texttospeech_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_theme_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_uiplugin.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_uitools.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_uitools_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_virtualkeyboard.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webchannel.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webchannel_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webengine.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webengine_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginecore.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginecore_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginewidgets.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_websockets.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_websockets_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webview.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_webview_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_widgets.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_widgets_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_winextras.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_winextras_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_xml.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_xml_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\modules\qt_lib_zlib_private.pri:
H:\Qt\Qt5.15.10-release\mkspecs\features\qt_functions.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\qt_config.prf:
H:\Qt\Qt5.15.10-release\mkspecs\win32-msvc\qmake.conf:
H:\Qt\Qt5.15.10-release\mkspecs\features\spec_post.prf:
.qmake.stash:
H:\Qt\Qt5.15.10-release\mkspecs\features\exclusive_builds.prf:
H:\Qt\Qt5.15.10-release\mkspecs\common\msvc-version.conf:
H:\Qt\Qt5.15.10-release\mkspecs\features\toolchain.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\default_pre.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\win32\default_pre.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\resolve_config.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\exclusive_builds_post.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\default_post.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\qml_debug.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\precompile_header.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\warn_on.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\qmake_use.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\file_copies.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\win32\windows.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\testcase_targets.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\exceptions.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\yacc.prf:
H:\Qt\Qt5.15.10-release\mkspecs\features\lex.prf:
pdfwidgets.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile pdfwidgets.pro -spec win32-msvc "CONFIG+=qml_debug"

qmake_all: sub-pdfviewer-qmake_all FORCE

make_first: sub-pdfviewer-make_first  FORCE
all: sub-pdfviewer-all  FORCE
clean: sub-pdfviewer-clean  FORCE
distclean: sub-pdfviewer-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-pdfviewer-install_subtargets FORCE
uninstall_subtargets: sub-pdfviewer-uninstall_subtargets FORCE

sub-pdfviewer-debug:
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-pdfviewer-debug

sub-pdfviewer-release:
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-pdfviewer-release

sub-pdfviewer-check:
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-pdfviewer-check

sub-pdfviewer-benchmark:
	@if not exist pdfviewer\ mkdir pdfviewer\ & if not exist pdfviewer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdfviewer\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\test\qt\pdfwidgets\pdfviewer\pdfviewer.pro -spec win32-msvc "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-pdfviewer-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

